### ISSUE TITLE
添加按钮悬浮菜单，暂时两个选项：新建笔记本或笔记

### ISSUE THREAD

**Issue by haoyang7** [yidongyingyongjishukaifa/JianYunNote#24]
参考https://blog.csdn.net/k571039838k/article/details/82386407

**Comment by haaok** [comment]
https://blog.csdn.net/a_zhon/article/details/74086025
https://blog.csdn.net/jdh99/article/details/71172128

**Comment by haaok** [comment]
输入弹出框
https://blog.csdn.net/feiqinbushizheng/article/details/78837711
