### ISSUE TITLE
写笔记使用markdown编辑器

### ISSUE THREAD

**Issue by haoyang7** [yidongyingyongjishukaifa/JianYunNote#8]

**Comment by Angelhand** [comment]
1

**Comment by haaok** [comment]
参考一下
https://blog.csdn.net/u013072976/article/details/51698196
https://blog.csdn.net/huangxiaoguo1/article/details/79062105
https://www.jianshu.com/p/a4d336f5b0ad
https://github.com/zzhoujay/RichText/issues

**Comment by haaok** [comment]
把这些类放到util包下
